[package]
name = "manga-mining-hub"
version = "2.0.1"
description = "A Tauri App"
authors = ["trandnquang"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "manga_mining_hub_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-shell = "2.0.0"
tauri-plugin-opener = "2.0.0"
tauri-plugin-dialog = "2.0.0"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "process", "io-util", "macros"] }
screenshots = "0.8"
enigo = "0.1.2"
image = "0.24"
lazy_static = "1.4.0"
reqwest = { version = "0.12", features = ["stream"] }
futures-util = "0.3"
zip = "0.6"
dirs = "5.0"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
